language: python
python:
  - "3.1"
  - "3.2"
before_install:
  - sudo apt-get install liblzma-dev
install:
  - "python setup.py install"
before_script:
  - "cd test"
script:
  - "python test_lzma.py"
